### PR TITLE
Verify results [SGP - 0010 ], [SGP - 0011]

### PR DESCRIPTION
**Pull request by Phyloiota**
# Welcome Community Node operators

We want to verify the outcome of the recently ended Governance vote events.

To do this, we need the help of our community node operators, who tracked these events.
 
### Event [SGP - 0010] -Tangle Community Grant Committee Grant Reviewer - **SHIMMER HORNET**

- Open a new tab in your browser.
   - If your **Shimmer Hornet** node runs on its own domain with HTTPS (like the recommended [Hornet docker setup](https://wiki.iota.org/hornet/how_tos/using_docker/) go to:
 `https://YOUR-NODES DOMAIN URL/api/participation/v1/events/0xe718e7f1d21c078109ef416c48b2b45f79e6d98d4ff2eb52334575bd8a7bf17e/status`
    (YOUR-NODEs DOMAIN URL should be your **own node**; otherwise, we all compare results from the same nodes)
   - If your node runs only HTTP go to:
`http://YOUR-NODES- IP-ADDRESS:14265/api/participation/v1/events/0xe718e7f1d21c078109ef416c48b2b45f79e6d98d4ff2eb52334575bd8a7bf17e/status`
    (YOUR-NODEs-IP - ADDRESS should be your **own node**, otherwise we all compare results from the same nodes)
 - If you use DLT.GREEN node-installer-docker:
press `E` in the dashboard and press `ENTER` to prove all events running on your node and compare following checksums

 Check that the status of the event is "**ended**"

### Event [SGP - 0011] - Tangle Community Grant Committee - Lead selection - **SHIMMER HORNET**

- Open a new tab in your browser.
   - If your **Shimmer Hornet** node runs on its own domain with HTTPS (like the recommended [Hornet docker setup](https://wiki.iota.org/hornet/how_tos/using_docker/) go to:
 `https://YOUR-NODES DOMAIN URL/api/participation/v1/events/0x632155305e889f29bbdf9da22c28794f99bab7a01a2a1188dde21cdaa8042171/status`
    (YOUR-NODEs DOMAIN URL should be your **own node**; otherwise, we all compare results from the same nodes)
   - If your node runs only HTTP go to:
`http://YOUR-NODES- IP-ADDRESS:14265/api/participation/v1/events/0x632155305e889f29bbdf9da22c28794f99bab7a01a2a1188dde21cdaa8042171/status`
    (YOUR-NODEs-IP - ADDRESS should be your **own node**, otherwise we all compare results from the same nodes)
 - If you use DLT.GREEN node-installer-docker:
press `E` in the dashboard and press `ENTER` to prove all events running on your node and compare following checksums

 Check that the status of the event is "**ended**"
 

### **Now compare all checksums of your node's event data with the following ones:**

- Event [SGP - 0010]: `0xbbecce078de9682793e20b6bad04013037016bdfb4d46b8dea42a221e36756ee`
- Event [SGP - 0011]: `0x121fa6fbf72df3b53ed39c25311c4294d5bbeaf3422a34ce8cff0193e4c214cd`

## **Leave an approving review on this Pull request or comment "approve" If your checksums in all events match. You can also add screenshots/proofs of your events in the comments to this PR.**

Thank you for contributing!

### CODE REVIEW

**Review by dlt-green — APPROVED** [review]
image

**Review by dlt-green — APPROVED** [review]
:white_check_mark: also files are checked and are ok

**Review by 0xKtota — COMMENTED** [review]
approve✅
photo_2024-07-02_15-43-12

**Comment by AlexTweeet** [comment]
approve ☑️

Bildschirmfoto 2024-07-02 um 17 22 47
Bildschirmfoto 2024-07-02 um 17 23 14

**Review by DerAnhalter — COMMENTED** [review]
pa-ev_01
pa-ev_02

**Review by no8ody — APPROVED** [review]
lgtm

Event [SGP - 0010]: `0xbbecce078de9682793e20b6bad04013037016bdfb4d46b8dea42a221e36756ee`
Event [SGP - 0011]: `0x121fa6fbf72df3b53ed39c25311c4294d5bbeaf3422a34ce8cff0193e4c214cd`

**Review by bogenlos — COMMENTED** [review]
image

**Review by bogenlos — COMMENTED** [review]
image

**Review by TimsonLabs — COMMENTED** [review]
✅ Checksums are fine


image

image

**Review by mag-node — COMMENTED** [review]
voting

**Review by vromvonbeyond — COMMENTED** [review]
image

image

**Review by DrWoyzeck — COMMENTED** [review]
image
image

**Comment by JannemanDev** [comment]
image

**Comment by TeeVeeEss** [comment]
[SGP - 0010]
```json
{"milestoneIndex":10673491,"status":"ended","questions":[{"answers":[{"value":1,"current":132904858909,"accumulated":15649778088780404},{"value":0,"current":3283766211,"accumulated":421093927658952},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":127774063766,"accumulated":15142936265997200},{"value":0,"current":8414561354,"accumulated":927935750442158},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":67478500123,"accumulated":8135906832500587},{"value":0,"current":68710124997,"accumulated":7934965183938770},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":44815944173,"accumulated":5366502136780932},{"value":0,"current":91372680947,"accumulated":10704369879658424},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":67375011970,"accumulated":8089678155853230},{"value":0,"current":68813613150,"accumulated":7981193860586127},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":74788304401,"accumulated":8676380419835313},{"value":0,"current":61400320719,"accumulated":7394491596604044},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":18721370523,"accumulated":2230873835404030},{"value":0,"current":117467254597,"accumulated":13839998181035328},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":18824112057,"accumulated":2226833145363432},{"value":0,"current":117364513063,"accumulated":13844038871075924},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":33008584855,"accumulated":3906520817854060},{"value":0,"current":103180040265,"accumulated":12164351198585296},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":68162485293,"accumulated":7927152094437843},{"value":0,"current":68026139827,"accumulated":8143719922001514},{"value":255,"current":0,"accumulated":0}]}],"checksum":"0xbbecce078de9682793e20b6bad04013037016bdfb4d46b8dea42a221e36756ee"}
```
[SGP - 0011]
```json
{"milestoneIndex":10673491,"status":"ended","questions":[{"answers":[{"value":1,"current":133604006047,"accumulated":15712083687806666},{"value":0,"current":811533469,"accumulated":77459008940321},{"value":255,"current":0,"accumulated":0}]}],"checksum":"0x121fa6fbf72df3b53ed39c25311c4294d5bbeaf3422a34ce8cff0193e4c214cd"}
```
LGTM!

**Review by TeeVeeEss — COMMENTED** [review]
LGTM

**Review by Tombaaa — COMMENTED** [review]
image

**Review by Dr-Electron — APPROVED** [review]
[SGP - 0010]
Checksum: `0xbbecce078de9682793e20b6bad04013037016bdfb4d46b8dea42a221e36756ee`

<details><summary>Details</summary>
<p>

```json
{
  "milestoneIndex": 10673491,
  "status": "ended",
  "questions": [
    {
      "answers": [
        {
          "value": 1,
          "current": 132904858909,
          "accumulated": 15649778088780404
        },
        {
          "value": 0,
          "current": 3283766211,
          "accumulated": 421093927658952
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 127774063766,
          "accumulated": 15142936265997200
        },
        {
          "value": 0,
          "current": 8414561354,
          "accumulated": 927935750442158
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 67478500123,
          "accumulated": 8135906832500587
        },
        {
          "value": 0,
          "current": 68710124997,
          "accumulated": 7934965183938770
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 44815944173,
          "accumulated": 5366502136780932
        },
        {
          "value": 0,
          "current": 91372680947,
          "accumulated": 10704369879658424
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 67375011970,
          "accumulated": 8089678155853230
        },
        {
          "value": 0,
          "current": 68813613150,
          "accumulated": 7981193860586127
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 74788304401,
          "accumulated": 8676380419835313
        },
        {
          "value": 0,
          "current": 61400320719,
          "accumulated": 7394491596604044
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 18721370523,
          "accumulated": 2230873835404030
        },
        {
          "value": 0,
          "current": 117467254597,
          "accumulated": 13839998181035328
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 18824112057,
          "accumulated": 2226833145363432
        },
        {
          "value": 0,
          "current": 117364513063,
          "accumulated": 13844038871075924
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 33008584855,
          "accumulated": 3906520817854060
        },
        {
          "value": 0,
          "current": 103180040265,
          "accumulated": 12164351198585296
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 68162485293,
          "accumulated": 7927152094437843
        },
        {
          "value": 0,
          "current": 68026139827,
          "accumulated": 8143719922001514
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    }
  ],
  "checksum": "0xbbecce078de9682793e20b6bad04013037016bdfb4d46b8dea42a221e36756ee"
}
```

</p>
</details>

[SGP - 0011]
Checksum: `0x121fa6fbf72df3b53ed39c25311c4294d5bbeaf3422a34ce8cff0193e4c214cd`

<details><summary>Details</summary>
<p>

```json
{
  "milestoneIndex": 10673491,
  "status": "ended",
  "questions": [
    {
      "answers": [
        {
          "value": 1,
          "current": 133604006047,
          "accumulated": 15712083687806666
        },
        {
          "value": 0,
          "current": 811533469,
          "accumulated": 77459008940321
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    }
  ],
  "checksum": "0x121fa6fbf72df3b53ed39c25311c4294d5bbeaf3422a34ce8cff0193e4c214cd"
}
```

</p>
</details>

**Review by CrashOverride-lab — COMMENTED** [review]
image

**Pull request merged**
