### PR TITLE
Verify results [SGP-0001], [SGP-0002], [SGP-0003], [SGP-0005]

### PR DESCRIPTION
**Pull request by Phyloiota**
### **Welcome Community Node operators**

We want to verify the outcome of the four recently ended Shimmer Governance vote event.

To do this, we need the help of our community node operators who tracked this event.

Please follow the next steps:

### **Event [SGP - 0001] Shimmer Community Grant Committee - Lead selection**

- Open a new tab in your browser 

- **If your node runs on its own domain with HTTPS (like the recommended [Hornet docker setup](https://wiki.iota.org/shimmer/hornet/how_tos/using_docker/)) go to:**   
`https://YOUR-NODES DOMAIN URL/api/participation/v1/events/0x8f757e3d09323ebf0629a8f2e4ab4dc8b9d2c628b97af00a82bd97a936335302/status`
    (YOUR-NODEs DOMAIN URL should be your **own node**; otherwise, we all compare results from the same nodes)
   
-  **If your node runs only HTTP go to:**
`http://YOUR-NODES- IP-ADDRESS:14265/api/participation/v1/events/0x8f757e3d09323ebf0629a8f2e4ab4dc8b9d2c628b97af00a82bd97a936335302/status`
    (YOUR-NODEs-IP - ADDRESS should be your **own node**, otherwise we all compare results from the same nodes)
    
 Check that the status of the event is "**ended**"

### **Event [SGP - 0002] Shimmer Community Grant Committee Grant Reviewer selection**

- Open a new tab in your browser 

- **If your node runs on its own domain with HTTPS (like the recommended [Hornet docker setup](https://wiki.iota.org/shimmer/hornet/how_tos/using_docker/)) go to:**   
`https://YOUR-NODES DOMAIN URL/api/participation/v1/events/0x199a401f5c26330b521f412c4f657517a7d1d075c0334f8d3a7670c1510e1f53/status`
    (YOUR-NODEs DOMAIN URL should be your **own node**, otherwise, we all compare results from the same nodes)
   
-  **If your node runs only HTTP go to:**
`http://YOUR-NODES- IP-ADDRESS:14265/api/participation/v1/events/0x199a401f5c26330b521f412c4f657517a7d1d075c0334f8d3a7670c1510e1f53/status`
    (YOUR-NODEs-IP - ADDRESS should be your **own node**, otherwise we all compare results from the same nodes)
    
 Check that the status of the event is "**ended**"

### **Event [SGP - 0003] Shimmer Growth Committee as part of the Tangle Ecosystem Association**

- Open a new tab in your browser 

- **If your node runs on its own domain with HTTPS (like the recommended [Hornet docker setup](https://wiki.iota.org/shimmer/hornet/how_tos/using_docker/)) go to:**   
`https://YOUR-NODES DOMAIN URL/api/participation/v1/events/0x66fd0a5be96d78918a55bcabc08a255d8ba63977b641c2ff1aef1cdd79ddfef4/status`
    (YOUR-NODEs DOMAIN URL should be your **own node**; otherwise, we all compare results from the same nodes)
   
-  **If your node runs only HTTP go to:**
`http://YOUR-NODES- IP-ADDRESS:14265/api/participation/v1/events/0x66fd0a5be96d78918a55bcabc08a255d8ba63977b641c2ff1aef1cdd79ddfef4/status`
    (YOUR-NODEs-IP - ADDRESS should be your **own node**, otherwise we all compare results from the same nodes)
    
 Check that the status of the event is "**ended**"

### **Event [SGP - 0005] Shimmer Community Treasury Grant Committee**

- Open a new tab in your browser 

- **If your node runs on its own domain with HTTPS (like the recommended [Hornet docker setup](https://wiki.iota.org/shimmer/hornet/how_tos/using_docker/)) go to:**   
`https://YOUR-NODES DOMAIN URL/api/participation/v1/events/0x1676eef80c31f2beaa561d349293c4386087c477eb3e4d818ae9fe119723f657/status`
    (YOUR-NODEs DOMAIN URL should be your **own node**; otherwise, we all compare results from the same nodes)
   
-  **If your node runs only HTTP go to:**
`http://YOUR-NODES- IP-ADDRESS:14265/api/participation/v1/events/0x1676eef80c31f2beaa561d349293c4386087c477eb3e4d818ae9fe119723f657/status`
    (YOUR-NODEs-IP - ADDRESS should be your **own node**, otherwise we all compare results from the same nodes)
    
 Check that the status of the event is "**ended**"

Now compare all checksums of your nodes event data with the following ones :
[SGP - 0001]: `0x868a88cbe6945955243efae20ac8f59a1653edd04cce1224781a7cbcbbc7f1af`
[SGP - 0002]: `0xa66a5209dc7c60af6b10ea1310df03a928c97ffd66e74e86fbf8510766ed6ad4`
[SGP - 0003]: `0xa11400990edc11df90e6aa80dfc78bb95431795335e5f105175495b88d3d94ba`
[SGP - 0004]: `0xafff377689438489c45b621595bc42a45186424619579cbbcdfc64464af58386`

Comment "approve" If your **checksums** in all events match. You can also add them in the comments to this PR.

### CODE REVIEW

**Comment by JannemanDev** [comment]
For my node `https://shimmer-hornet1.boxathome.net` all checksums match! Can't see any Approve button though?!

Event [SGP - 0001] Shimmer Community Grant Committee - Lead selection:
```json
{"milestoneIndex":3176300,"status":"ended","questions":[{"answers":[{"value":1,"current":103650433574,"accumulated":12384530299988155},{"value":2,"current":11251826120,"accumulated":1410549256294991},{"value":3,"current":1360865879,"accumulated":170225198866668},{"value":0,"current":2091592018,"accumulated":241423488513308},{"value":255,"current":0,"accumulated":0}]}],"checksum":"0x868a88cbe6945955243efae20ac8f59a1653edd04cce1224781a7cbcbbc7f1af"}
```

Event [SGP - 0002] Shimmer Community Grant Committee Grant Reviewer selection:
```json
{"milestoneIndex":3176300,"status":"ended","questions":[{"answers":[{"value":1,"current":130700995695,"accumulated":15375945551078377},{"value":0,"current":8919523939,"accumulated":1032168530002346},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":117958305960,"accumulated":13913136033786009},{"value":0,"current":21662213674,"accumulated":2494978047294714},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":43891059185,"accumulated":4969738889745140},{"value":0,"current":95729460449,"accumulated":11438375191335583},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":86048843589,"accumulated":10357355610584491},{"value":0,"current":53571676045,"accumulated":6050758470496232},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":94861136768,"accumulated":11450158922528068},{"value":0,"current":44759382866,"accumulated":4957955158552655},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":62148692254,"accumulated":7438066114248679},{"value":0,"current":77471827380,"accumulated":8970047966832044},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":75646801337,"accumulated":9117283841071882},{"value":0,"current":63973718297,"accumulated":7290830240008841},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":10138516240,"accumulated":1212974718740549},{"value":0,"current":129482003394,"accumulated":15195139362340174},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":10123014935,"accumulated":1220376779808322},{"value":0,"current":129497504699,"accumulated":15187737301272401},{"value":255,"current":0,"accumulated":0}]},{"answers":[{"value":1,"current":73306228340,"accumulated":8870413625967111},{"value":0,"current":66314291294,"accumulated":7537700455113612},{"value":255,"current":0,"accumulated":0}]}],"checksum":"0xa66a5209dc7c60af6b10ea1310df03a928c97ffd66e74e86fbf8510766ed6ad4"}
```

Event [SGP - 0003] Shimmer Growth Committee as part of the Tangle Ecosystem Association
```json
{"milestoneIndex":3176300,"status":"ended","questions":[{"answers":[{"value":1,"current":134923646158,"accumulated":15871642706278575},{"value":2,"current":1590543290,"accumulated":214275025327008},{"value":0,"current":983960301,"accumulated":106139044272059},{"value":255,"current":0,"accumulated":0}]}],"checksum":"0xa11400990edc11df90e6aa80dfc78bb95431795335e5f105175495b88d3d94ba"}
```

Event [SGP - 0005] Shimmer Community Treasury Grant Committee
```json
{"milestoneIndex":3176300,"status":"ended","questions":[{"answers":[{"value":1,"current":135684135890,"accumulated":15968734665057647},{"value":2,"current":1444700307,"accumulated":197528068091018},{"value":0,"current":543799488,"accumulated":52833476056133},{"value":255,"current":0,"accumulated":0}]}],"checksum":"0xafff377689438489c45b621595bc42a45186424619579cbbcdfc64464af58386"}
```

**Comment by WernerderChamp** [comment]
- 0x8f757e3d09323ebf0629a8f2e4ab4dc8b9d2c628b97af00a82bd97a936335302 -> 0x868a88cbe6945955243efae20ac8f59a1653edd04cce1224781a7cbcbbc7f1af
- 0x199a401f5c26330b521f412c4f657517a7d1d075c0334f8d3a7670c1510e1f53 -> 0xa66a5209dc7c60af6b10ea1310df03a928c97ffd66e74e86fbf8510766ed6ad4
- 0x66fd0a5be96d78918a55bcabc08a255d8ba63977b641c2ff1aef1cdd79ddfef4 -> 0xa11400990edc11df90e6aa80dfc78bb95431795335e5f105175495b88d3d94ba
- 0x1676eef80c31f2beaa561d349293c4386087c477eb3e4d818ae9fe119723f657 -> 0xafff377689438489c45b621595bc42a45186424619579cbbcdfc64464af58386

All checksums matching

**Comment by ockerocker** [comment]
SGP - 0001]:

0x868a88cbe6945955243efae20ac8f59a1653edd04cce1224781a7cbcbbc7f1af

[SGP - 0002]: 

0xa66a5209dc7c60af6b10ea1310df03a928c97ffd66e74e86fbf8510766ed6ad4

[SGP - 0003]: 

0xa11400990edc11df90e6aa80dfc78bb95431795335e5f105175495b88d3d94ba

[SGP - 0005]:

0xafff377689438489c45b621595bc42a45186424619579cbbcdfc64464af58386

**Comment by 2g4y1** [comment]
Screenshot_20230330-160825

**Comment by bogenlos** [comment]
approve

image

**Comment by Travetown** [comment]
approve 
image

**Comment by gobbli** [comment]
**approve**

image

**Comment by Danlino** [comment]
[SGP - 0001]
   event: 0x8f757e3d09323ebf0629a8f2e4ab4dc8b9d2c628b97af00a82bd97a936335302
checksum: 0x868a88cbe6945955243efae20ac8f59a1653edd04cce1224781a7cbcbbc7f1af

[SGP - 0002]
   event: 0x199a401f5c26330b521f412c4f657517a7d1d075c0334f8d3a7670c1510e1f53
checksum: 0xa66a5209dc7c60af6b10ea1310df03a928c97ffd66e74e86fbf8510766ed6ad4

[SGP - 0003]
   event: 0x66fd0a5be96d78918a55bcabc08a255d8ba63977b641c2ff1aef1cdd79ddfef4
checksum: 0xa11400990edc11df90e6aa80dfc78bb95431795335e5f105175495b88d3d94ba

[SGP - 0005]
   event: 0x1676eef80c31f2beaa561d349293c4386087c477eb3e4d818ae9fe119723f657
checksum: 0xafff377689438489c45b621595bc42a45186424619579cbbcdfc64464af58386

**Comment by DerAnhalter** [comment]
- event: 0x8f757e3d09323ebf0629a8f2e4ab4dc8b9d2c628b97af00a82bd97a936335302
checksum "0x868a88cbe6945955243efae20ac8f59a1653edd04cce1224781a7cbcbbc7f1af" 👍

- events: 0x199a401f5c26330b521f412c4f657517a7d1d075c0334f8d3a7670c1510e1f53
checksum "0xa66a5209dc7c60af6b10ea1310df03a928c97ffd66e74e86fbf8510766ed6ad4" 👍

- events: 0x66fd0a5be96d78918a55bcabc08a255d8ba63977b641c2ff1aef1cdd79ddfef4
checksum "0xa11400990edc11df90e6aa80dfc78bb95431795335e5f105175495b88d3d94ba" 👍

- events: 0x1676eef80c31f2beaa561d349293c4386087c477eb3e4d818ae9fe119723f657
checksum "0xafff377689438489c45b621595bc42a45186424619579cbbcdfc64464af58386" 👍

**Review by fhb191309 — COMMENTED** [review]
Approved 

event_verification_purkdrf-dltgreen

**Review by vromvonbeyond — COMMENTED** [review]
image

**Comment by vromvonbeyond** [comment]
image

**Review by dlt-green — COMMENTED** [review]
image

**Comment by martinDSC10** [comment]
approve
vote

**Comment by uknawn** [comment]
Approve

image

**Review by 0xKtota — COMMENTED** [review]
Approve
image

**Review by martinDSC10 — COMMENTED** [review]
vote

**Comment by Konjunktiv** [comment]
image

**Review by AlexTweeet — COMMENTED** [review]
approve
review

**Comment by mogulbuster** [comment]
SGP - 0001
SGP - 0002
SGP - 0003
SGP - 0004

**Review by DrWoyzeck — COMMENTED** [review]
approve

speedo

**Review by ockerocker — COMMENTED** [review]
SGP - 0001]:

0x868a88cbe6945955243efae20ac8f59a1653edd04cce1224781a7cbcbbc7f1af

[SGP - 0002]:

0xa66a5209dc7c60af6b10ea1310df03a928c97ffd66e74e86fbf8510766ed6ad4

[SGP - 0003]:

0xa11400990edc11df90e6aa80dfc78bb95431795335e5f105175495b88d3d94ba

[SGP - 0005]:

0xafff377689438489c45b621595bc42a45186424619579cbbcdfc64464af58386

**Comment by HolgerKoether** [comment]
Validity of posted hashes hereby confirmed by SPYCE.5.
(SOURCE will be removed latest on 3rd of April 2023.)

SGP - 0001:
0x868a88cbe6945955243efae20ac8f59a1653edd04cce1224781a7cbcbbc7f1af

SOURCE:
https://condescending-snyder.node.spyce5.com/api/participation/v1/events/0x8f757e3d09323ebf0629a8f2e4ab4dc8b9d2c628b97af00a82bd97a936335302/status



SGP - 0002:
0xa66a5209dc7c60af6b10ea1310df03a928c97ffd66e74e86fbf8510766ed6ad4

SOURCE:
https://condescending-snyder.node.spyce5.com/api/participation/v1/events/0x199a401f5c26330b521f412c4f657517a7d1d075c0334f8d3a7670c1510e1f53/status



SGP - 0003:
0xa11400990edc11df90e6aa80dfc78bb95431795335e5f105175495b88d3d94ba

SOURCE:
https://condescending-snyder.node.spyce5.com/api/participation/v1/events/0x66fd0a5be96d78918a55bcabc08a255d8ba63977b641c2ff1aef1cdd79ddfef4/status



SGP - 0005:
0xafff377689438489c45b621595bc42a45186424619579cbbcdfc64464af58386

SOURCE:
https://condescending-snyder.node.spyce5.com/api/participation/v1/events/0x1676eef80c31f2beaa561d349293c4386087c477eb3e4d818ae9fe119723f657/status

**Comment by Tombaaa** [comment]
Approve
image

**Comment by igrand90** [comment]
Approved
Screenshot 2023-03-31 161816

**Comment by janviehweger** [comment]
Address: shimmer.viehweger.it:443 (JWT-Token for API Access randomly generated)

───────────────────────────────────────────────────────────────────────────────
Name: [SGP - 0005] - Shimmer Community Grant Committee
Status: ended Milestone index: 3176300

Event ID: 0x1676eef80c31f2beaa561d349293c4386087c477eb3e4d818ae9fe119723f657
Checksum: 0xafff377689438489c45b621595bc42a45186424619579cbbcdfc64464af58386

Total rewards:  Symbol: null
───────────────────────────────────────────────────────────────────────────────
───────────────────────────────────────────────────────────────────────────────
Name: [SGP - 0002] Shimmer Community Grant Committee Grant Reviewer selection
Status: ended Milestone index: 3176300

Event ID: 0x199a401f5c26330b521f412c4f657517a7d1d075c0334f8d3a7670c1510e1f53
Checksum: 0xa66a5209dc7c60af6b10ea1310df03a928c97ffd66e74e86fbf8510766ed6ad4

Total rewards:  Symbol: null
───────────────────────────────────────────────────────────────────────────────
───────────────────────────────────────────────────────────────────────────────
Name: [SGP - 0003] Shimmer Growth Committee as part of the Tangle Ecosystem Association
Status: ended Milestone index: 3176300

Event ID: 0x66fd0a5be96d78918a55bcabc08a255d8ba63977b641c2ff1aef1cdd79ddfef4
Checksum: 0xa11400990edc11df90e6aa80dfc78bb95431795335e5f105175495b88d3d94ba

Total rewards:  Symbol: null
───────────────────────────────────────────────────────────────────────────────
───────────────────────────────────────────────────────────────────────────────
Name: [SGP - 0001] Shimmer Community Grant Committee - Lead selection
Status: ended Milestone index: 3176300

Event ID: 0x8f757e3d09323ebf0629a8f2e4ab4dc8b9d2c628b97af00a82bd97a936335302
Checksum: 0x868a88cbe6945955243efae20ac8f59a1653edd04cce1224781a7cbcbbc7f1af

Total rewards:  Symbol: null
───────────────────────────────────────────────────────────────────────────────

**Comment by tristanc39** [comment]
Event [SGP - 0001]
"status":"ended"
"checksum":"0x868a88cbe6945955243efae20ac8f59a1653edd04cce1224781a7cbcbbc7f1af"

Event [SGP - 0002]
"status":"ended"
"checksum":"0xa66a5209dc7c60af6b10ea1310df03a928c97ffd66e74e86fbf8510766ed6ad4"

Event [SGP - 0003]
"status":"ended"
"checksum":"0xa11400990edc11df90e6aa80dfc78bb95431795335e5f105175495b88d3d94ba"

Event [SGP - 0005]
"status":"ended
"checksum":"0xafff377689438489c45b621595bc42a45186424619579cbbcdfc64464af58386"

approve

**Review by TimsonLabs — COMMENTED** [review]
approve

image

**Review by CryptoFutta — COMMENTED** [review]
approve


230403_Event-verification

**Pull request merged**
