### PR TITLE
Verify Results [SGP - 0007, SGP - 0008, SGP - 0009, IGP - 0002, IGP - 0003, IGP - 0004]

### PR DESCRIPTION
**Pull request by dlt-green**
# Welcome Community Node operators

We want to verify the outcome of the recently ended Governance vote events.

To do this, we need the help of our community node operators, who tracked these events.
 
### Event [SGP - 0007] - Tangle Community Treasury Term 2024 to 2025 - **SHIMMER HORNET**

- Open a new tab in your browser.
   - If your **Shimmer Hornet** node runs on its own domain with HTTPS (like the recommended [Hornet docker setup](https://wiki.iota.org/hornet/how_tos/using_docker/) go to:
 `https://YOUR-NODES DOMAIN URL/api/participation/v1/events/0x69194943b788eb67bfd3b1e258041af1cbb8f501489c5d826e6cd970cfaf01eb/status`
    (YOUR-NODEs DOMAIN URL should be your **own node**; otherwise, we all compare results from the same nodes)
   - If your node runs only HTTP go to:
`http://YOUR-NODES- IP-ADDRESS:14265/api/participation/v1/events/0x69194943b788eb67bfd3b1e258041af1cbb8f501489c5d826e6cd970cfaf01eb/status`
    (YOUR-NODEs-IP - ADDRESS should be your **own node**, otherwise we all compare results from the same nodes)
 - If you use DLT.GREEN node-installer-docker:
press `E` in the dashboard and press `ENTER` to prove all events running on your node and compare following checksums

 Check that the status of the event is "**ended**"

### Event [SGP - 0008] - Tangle Community Grant Committee Reviewer selection - **SHIMMER HORNET**

- Open a new tab in your browser.
   - If your **Shimmer Hornet** node runs on its own domain with HTTPS (like the recommended [Hornet docker setup](https://wiki.iota.org/hornet/how_tos/using_docker/) go to:
 `https://YOUR-NODES DOMAIN URL/api/participation/v1/events/0xf537ce0f5f18726057342f9c66ce69da242f827a7b712e466a5ba56acf7b6b55/status`
    (YOUR-NODEs DOMAIN URL should be your **own node**; otherwise, we all compare results from the same nodes)
   - If your node runs only HTTP go to:
`http://YOUR-NODES- IP-ADDRESS:14265/api/participation/v1/events/0xf537ce0f5f18726057342f9c66ce69da242f827a7b712e466a5ba56acf7b6b55/status`
    (YOUR-NODEs-IP - ADDRESS should be your **own node**, otherwise we all compare results from the same nodes)
 - If you use DLT.GREEN node-installer-docker:
press `E` in the dashboard and press `ENTER` to prove all events running on your node and compare following checksums

 Check that the status of the event is "**ended**"
 
 ### Event [SGP - 0009] - Tangle Community Grant Committee - Lead selection - **SHIMMER HORNET**

- Open a new tab in your browser.
   - If your **Shimmer Hornet** node runs on its own domain with HTTPS (like the recommended [Hornet docker setup](https://wiki.iota.org/hornet/how_tos/using_docker/) go to:
 `https://YOUR-NODES DOMAIN URL/api/participation/v1/events/0x32dd81b45c36c67f5d1d9b218d023aa3a658f17c485caeb8300e6f5b9136b91c/status`
    (YOUR-NODEs DOMAIN URL should be your **own node**; otherwise, we all compare results from the same nodes)
   - If your node runs only HTTP go to:
`http://YOUR-NODES- IP-ADDRESS:14265/api/participation/v1/events/0x32dd81b45c36c67f5d1d9b218d023aa3a658f17c485caeb8300e6f5b9136b91c/status`
    (YOUR-NODEs-IP - ADDRESS should be your **own node**, otherwise we all compare results from the same nodes)
 - If you use DLT.GREEN node-installer-docker:
press `E` in the dashboard and press `ENTER` to prove all events running on your node and compare following checksums

 Check that the status of the event is "**ended**"

### Event [IGP - 0002] - Tangle Community Treasury Term 2024 to 2025 - **IOTA HORNET**

- Open a new tab in your browser.
   - If your **IOTA Hornet** node runs on its own domain with HTTPS (like the recommended [Hornet docker setup](https://wiki.iota.org/hornet/how_tos/using_docker/) go to:
 `https://YOUR-NODES DOMAIN URL/api/participation/v1/events/0x0a2e8afc01146f6283233e7d69fbd1a7455078f239fd33a22c05bf2c529ed633/status`
    (YOUR-NODEs DOMAIN URL should be your **own node**; otherwise, we all compare results from the same nodes)
   - If your node runs only HTTP go to:
`http://YOUR-NODES- IP-ADDRESS:14265/api/participation/v1/events/0x0a2e8afc01146f6283233e7d69fbd1a7455078f239fd33a22c05bf2c529ed633/status`
    (YOUR-NODEs-IP - ADDRESS should be your **own node**, otherwise we all compare results from the same nodes)
 - If you use DLT.GREEN node-installer-docker:
press `E` in the dashboard and press `ENTER` to prove all events running on your node and compare following checksums

 Check that the status of the event is "**ended**"

### Event [IGP - 0003] - Tangle Community Grant Committee Reviewer selection - **IOTA HORNET**

- Open a new tab in your browser.
   - If your **IOTA Hornet** node runs on its own domain with HTTPS (like the recommended [Hornet docker setup](https://wiki.iota.org/hornet/how_tos/using_docker/) go to:
 `https://YOUR-NODES DOMAIN URL/api/participation/v1/events/0x91ca895ef442d3266537fa5e73736bc774bea2571a85fbf4451d44c236311a5c/status`
    (YOUR-NODEs DOMAIN URL should be your **own node**; otherwise, we all compare results from the same nodes)
   - If your node runs only HTTP go to:
`http://YOUR-NODES- IP-ADDRESS:14265/api/participation/v1/events/0x91ca895ef442d3266537fa5e73736bc774bea2571a85fbf4451d44c236311a5c/status`
    (YOUR-NODEs-IP - ADDRESS should be your **own node**, otherwise we all compare results from the same nodes)
 - If you use DLT.GREEN node-installer-docker:
press `E` in the dashboard and press `ENTER` to prove all events running on your node and compare following checksums

 Check that the status of the event is "**ended**"
 
 ### Event [IGP - 0004] - Tangle Community Grant Committee - Lead selection - **IOTA HORNET**

- Open a new tab in your browser.
   - If your **IOTA Hornet** node runs on its own domain with HTTPS (like the recommended [Hornet docker setup](https://wiki.iota.org/hornet/how_tos/using_docker/) go to:
 `https://YOUR-NODES DOMAIN URL/api/participation/v1/events/0xcd46807cf026c9eab7245bb9d11f51ae4c60fde2f1bed830520beb14adba412a/status`
    (YOUR-NODEs DOMAIN URL should be your **own node**; otherwise, we all compare results from the same nodes)
   - If your node runs only HTTP go to:
`http://YOUR-NODES- IP-ADDRESS:14265/api/participation/v1/events/0xcd46807cf026c9eab7245bb9d11f51ae4c60fde2f1bed830520beb14adba412a/status`
    (YOUR-NODEs-IP - ADDRESS should be your **own node**, otherwise we all compare results from the same nodes)
 - If you use DLT.GREEN node-installer-docker:
press `E` in the dashboard and press `ENTER` to prove all events running on your node and compare following checksums

 Check that the status of the event is "**ended**"

### **Now compare all checksums of your node's event data with the following ones:**

SHIMMER-NETWORK:

- Event [SGP - 0007]: `0x9c11e23e2e07fed929552396c593b03a977076c426c9814f368f4067e5b36148`
- Event [SGP - 0008]: `0xd88a182c39dc6cac7b9084baeb08f059db3df34e772d36fa86cdbc9fe6abc181`
- Event [SGP - 0009]: `0x86e0ff7dad53ceb8317af946e45639fc9940daa71d94aabc788f055f221aea76`

IOTA-NETWORK:

- Event [IGP - 0002]: `0x7096c8591a3004a6167b336a2f163b210e967686471fcd05ee52cdbaeaa7c95c`
- Event [IGP - 0003]: `0x4d02f7823975a872de2df3d0f8ef1b47a71121367dcfe102dc4736066127bcf3`
- Event [IGP - 0004]: `0x76d8e9ca9239a8c086263fe64d8fdb06602b2b984af420c697a4dc1d34726d6e`

## **Leave an approving review on this Pull request or comment "approve" If your checksums in all events match. You can also add screenshots/proofs of your events in the comments to this PR.**

Thank you for contributing!

### CODE REVIEW

**Review by dlt-green — COMMENTED** [review]
image

**Review by CrashOverride-lab — COMMENTED** [review]
image

**Review by 0xKtota — COMMENTED** [review]
Shimmer:
image

**Review by HerrSkull — COMMENTED** [review]
image

**Review by martinDSC10 — COMMENTED** [review]
image

**Review by bogenlos — COMMENTED** [review]
Screenshot_20240326-214739_JuiceSSH

**Review by p00dl — COMMENTED** [review]
image

**Review by vromvonbeyond — COMMENTED** [review]
image

**Review by vromvonbeyond — COMMENTED** [review]
image

**Review by ockerocker — COMMENTED** [review]
Event [SGP - 0007]:

Bildschirmfoto vom 2024-03-26 23-02-24

Event [SGP - 0008]:

Bildschirmfoto vom 2024-03-26 22-58-34

Event [SGP - 0009]:

Bildschirmfoto vom 2024-03-26 23-05-38

**Comment by dlt-green** [comment]
> My IOTA node: image
> 
> My Shimmer node: image

@vromvonbeyond the first picture is not showing your iota node (both pictures are the same from your shimmer node) - also this is the PR for reviewing the events on the shimmer network, so your iota node is not needed here in the moment. for the events on the iota network, there will come an additionally PR.

**Comment by dlt-green** [comment]
image

**Review by cbries — COMMENTED** [review]
image

**Review by vromvonbeyond — COMMENTED** [review]
image

**Review by fhb191309 — COMMENTED** [review]
Bildschirmfoto 2024-03-27 um 08 19 06
Bildschirmfoto 2024-03-27 um 08 18 09

**Review by bogenlos — COMMENTED** [review]
image

**Comment by JannemanDev** [comment]
I only tracked the 3 IOTA Events:

image

**Review by AlexTweeet — COMMENTED** [review]
Bildschirmfoto 2024-03-27 um 09 03 50
Bildschirmfoto 2024-03-27 um 09 06 39

**Review by TimsonLabs — COMMENTED** [review]
- IOTA network: checksums of all 3 events are ok
- Shimmer network: checksums of all 3 events are ok

IOTA

Shimmer

**Review by CryptoFutta — COMMENTED** [review]
240327_Image1

**Review by martinDSC10 — COMMENTED** [review]
IOTA event
image

**Review by CryptoFutta — COMMENTED** [review]
240327_Image_GitHub

**Review by no8ody — APPROVED** [review]
Ballot ID: "0x69194943b788eb67bfd3b1e258041af1cbb8f501489c5d826e6cd970cfaf01eb"
Checksum: "0x9c11e23e2e07fed929552396c593b03a977076c426c9814f368f4067e5b36148"

Ballot ID: "0xf537ce0f5f18726057342f9c66ce69da242f827a7b712e466a5ba56acf7b6b55"
Checksum: "0xd88a182c39dc6cac7b9084baeb08f059db3df34e772d36fa86cdbc9fe6abc181"

Ballot ID: "0x32dd81b45c36c67f5d1d9b218d023aa3a658f17c485caeb8300e6f5b9136b91c"
Checksum: "0x86e0ff7dad53ceb8317af946e45639fc9940daa71d94aabc788f055f221aea76"

Ballot ID: "0x0a2e8afc01146f6283233e7d69fbd1a7455078f239fd33a22c05bf2c529ed633"
Checksum: "0x7096c8591a3004a6167b336a2f163b210e967686471fcd05ee52cdbaeaa7c95c"

Ballot ID: "0x91ca895ef442d3266537fa5e73736bc774bea2571a85fbf4451d44c236311a5c"
Checksum: "0x4d02f7823975a872de2df3d0f8ef1b47a71121367dcfe102dc4736066127bcf3"

Ballot ID: "0xcd46807cf026c9eab7245bb9d11f51ae4c60fde2f1bed830520beb14adba412a"
Checksum: "0x76d8e9ca9239a8c086263fe64d8fdb06602b2b984af420c697a4dc1d34726d6e"

**Review by ockerocker — COMMENTED** [review]
Event [IGP - 0002]:

Bildschirmfoto vom 2024-03-27 10-25-42

Event [IGP - 0003]:

Bildschirmfoto vom 2024-03-27 10-27-28

Event [IGP - 0004]:

Bildschirmfoto vom 2024-03-27 10-29-00

**Comment by TeeVeeEss** [comment]
IGP - 002:
```json
{
  "milestoneIndex": 10488887,
  "status": "ended",
  "questions": [
    {
      "answers": [
        {
          "value": 1,
          "current": 206768710534,
          "accumulated": 23773200339766836
        },
        {
          "value": 2,
          "current": 6611603991,
          "accumulated": 787646969587607
        },
        {
          "value": 0,
          "current": 636266867,
          "accumulated": 68542185853753
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    }
  ],
  "checksum": "0x7096c8591a3004a6167b336a2f163b210e967686471fcd05ee52cdbaeaa7c95c"
}
```
IGP - 003:
```json
{
  "milestoneIndex": 10488887,
  "status": "ended",
  "questions": [
    {
      "answers": [
        {
          "value": 1,
          "current": 180228296226,
          "accumulated": 20810751733860144
        },
        {
          "value": 0,
          "current": 7344839886,
          "accumulated": 733273016534623
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 172216710537,
          "accumulated": 19923852112757044
        },
        {
          "value": 0,
          "current": 15356425575,
          "accumulated": 1620172637637723
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 124645871213,
          "accumulated": 14854340515302212
        },
        {
          "value": 0,
          "current": 62927264899,
          "accumulated": 6689684235092557
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 87419575530,
          "accumulated": 9873818627451860
        },
        {
          "value": 0,
          "current": 100153560582,
          "accumulated": 11670206122942908
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 76190741665,
          "accumulated": 9104830290378926
        },
        {
          "value": 0,
          "current": 111382394447,
          "accumulated": 12439194460015842
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 135645573452,
          "accumulated": 15525546539743980
        },
        {
          "value": 0,
          "current": 51927562660,
          "accumulated": 6018478210650788
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 123764519112,
          "accumulated": 14673394727471922
        },
        {
          "value": 0,
          "current": 63808617000,
          "accumulated": 6870630022922846
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 28567730036,
          "accumulated": 3382698480450231
        },
        {
          "value": 0,
          "current": 159005406076,
          "accumulated": 18161326269944536
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    }
  ],
  "checksum": "0x4d02f7823975a872de2df3d0f8ef1b47a71121367dcfe102dc4736066127bcf3"
}
```
IGP - 004:
```json
{
  "milestoneIndex": 10488887,
  "status": "ended",
  "questions": [
    {
      "answers": [
        {
          "value": 1,
          "current": 144175673377,
          "accumulated": 17222953076567388
        },
        {
          "value": 0,
          "current": 17293787962,
          "accumulated": 1229890487133415
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    }
  ],
  "checksum": "0x76d8e9ca9239a8c086263fe64d8fdb06602b2b984af420c697a4dc1d34726d6e"
}
```

**Review by TeeVeeEss — COMMENTED** [review]
IGP - 002:
```json
{
  "milestoneIndex": 10488887,
  "status": "ended",
  "questions": [
    {
      "answers": [
        {
          "value": 1,
          "current": 206768710534,
          "accumulated": 23773200339766836
        },
        {
          "value": 2,
          "current": 6611603991,
          "accumulated": 787646969587607
        },
        {
          "value": 0,
          "current": 636266867,
          "accumulated": 68542185853753
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    }
  ],
  "checksum": "0x7096c8591a3004a6167b336a2f163b210e967686471fcd05ee52cdbaeaa7c95c"
}
```
IGP - 003:
```json
{
  "milestoneIndex": 10488887,
  "status": "ended",
  "questions": [
    {
      "answers": [
        {
          "value": 1,
          "current": 180228296226,
          "accumulated": 20810751733860144
        },
        {
          "value": 0,
          "current": 7344839886,
          "accumulated": 733273016534623
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 172216710537,
          "accumulated": 19923852112757044
        },
        {
          "value": 0,
          "current": 15356425575,
          "accumulated": 1620172637637723
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 124645871213,
          "accumulated": 14854340515302212
        },
        {
          "value": 0,
          "current": 62927264899,
          "accumulated": 6689684235092557
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 87419575530,
          "accumulated": 9873818627451860
        },
        {
          "value": 0,
          "current": 100153560582,
          "accumulated": 11670206122942908
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 76190741665,
          "accumulated": 9104830290378926
        },
        {
          "value": 0,
          "current": 111382394447,
          "accumulated": 12439194460015842
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 135645573452,
          "accumulated": 15525546539743980
        },
        {
          "value": 0,
          "current": 51927562660,
          "accumulated": 6018478210650788
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 123764519112,
          "accumulated": 14673394727471922
        },
        {
          "value": 0,
          "current": 63808617000,
          "accumulated": 6870630022922846
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    },
    {
      "answers": [
        {
          "value": 1,
          "current": 28567730036,
          "accumulated": 3382698480450231
        },
        {
          "value": 0,
          "current": 159005406076,
          "accumulated": 18161326269944536
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    }
  ],
  "checksum": "0x4d02f7823975a872de2df3d0f8ef1b47a71121367dcfe102dc4736066127bcf3"
}
```
IGP - 004:
```json
{
  "milestoneIndex": 10488887,
  "status": "ended",
  "questions": [
    {
      "answers": [
        {
          "value": 1,
          "current": 144175673377,
          "accumulated": 17222953076567388
        },
        {
          "value": 0,
          "current": 17293787962,
          "accumulated": 1229890487133415
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    }
  ],
  "checksum": "0x76d8e9ca9239a8c086263fe64d8fdb06602b2b984af420c697a4dc1d34726d6e"
}
```

**Review by Tombaaa — COMMENTED** [review]
image

**Review by Tombaaa — COMMENTED** [review]
image

**Review by Konjunktiv — COMMENTED** [review]
image

**Review by Konjunktiv — COMMENTED** [review]
image

**Review by 0xKtota — COMMENTED** [review]
IOTA:
image

**Review by CrashOverride-lab — COMMENTED** [review]
image

**Comment by mogulbuster** [comment]
Screenshot 2024-03-27 at 21 40 28
Screenshot 2024-03-27 at 21 50 46

**Review by DrWoyzeck — COMMENTED** [review]
Event_1

**Review by DrWoyzeck — COMMENTED** [review]
image

**Comment by uknawn** [comment]
image

image

Approved

**Review by uknawn — COMMENTED** [review]
Approved

image

image

**Comment by DerAnhalter** [comment]
.../events/0x69194943b788eb67bfd3b1e258041af1cbb8f501489c5d826e6cd970cfaf01eb/status
"checksum": "0x9c11e23e2e07fed929552396c593b03a977076c426c9814f368f4067e5b36148"

../events/0xf537ce0f5f18726057342f9c66ce69da242f827a7b712e466a5ba56acf7b6b55/status
"checksum": "0xd88a182c39dc6cac7b9084baeb08f059db3df34e772d36fa86cdbc9fe6abc181"

.../events/0x32dd81b45c36c67f5d1d9b218d023aa3a658f17c485caeb8300e6f5b9136b91c/status
"checksum": "0x86e0ff7dad53ceb8317af946e45639fc9940daa71d94aabc788f055f221aea76"

.../events/0x0a2e8afc01146f6283233e7d69fbd1a7455078f239fd33a22c05bf2c529ed633/status
"checksum": "0x7096c8591a3004a6167b336a2f163b210e967686471fcd05ee52cdbaeaa7c95c"

.../events/0x91ca895ef442d3266537fa5e73736bc774bea2571a85fbf4451d44c236311a5c/status
"checksum": "0x4d02f7823975a872de2df3d0f8ef1b47a71121367dcfe102dc4736066127bcf3"

.../events/0xcd46807cf026c9eab7245bb9d11f51ae4c60fde2f1bed830520beb14adba412a/status
"checksum": "0x76d8e9ca9239a8c086263fe64d8fdb06602b2b984af420c697a4dc1d34726d6e"

**Review by DerAnhalter — COMMENTED** [review]
.../events/0x69194943b788eb67bfd3b1e258041af1cbb8f501489c5d826e6cd970cfaf01eb/status
"checksum": "0x9c11e23e2e07fed929552396c593b03a977076c426c9814f368f4067e5b36148"

../events/0xf537ce0f5f18726057342f9c66ce69da242f827a7b712e466a5ba56acf7b6b55/status
"checksum": "0xd88a182c39dc6cac7b9084baeb08f059db3df34e772d36fa86cdbc9fe6abc181"

.../events/0x32dd81b45c36c67f5d1d9b218d023aa3a658f17c485caeb8300e6f5b9136b91c/status
"checksum": "0x86e0ff7dad53ceb8317af946e45639fc9940daa71d94aabc788f055f221aea76"

.../events/0x0a2e8afc01146f6283233e7d69fbd1a7455078f239fd33a22c05bf2c529ed633/status
"checksum": "0x7096c8591a3004a6167b336a2f163b210e967686471fcd05ee52cdbaeaa7c95c"

.../events/0x91ca895ef442d3266537fa5e73736bc774bea2571a85fbf4451d44c236311a5c/status
"checksum": "0x4d02f7823975a872de2df3d0f8ef1b47a71121367dcfe102dc4736066127bcf3"

.../events/0xcd46807cf026c9eab7245bb9d11f51ae4c60fde2f1bed830520beb14adba412a/status
"checksum": "0x76d8e9ca9239a8c086263fe64d8fdb06602b2b984af420c697a4dc1d34726d6e"

**Review by Phyloiota — APPROVED** [review]

**Review by Dr-Electron — APPROVED** [review]

**Pull request merged**
