### PR TITLE
Verify Results [IGP - 0005] A Proposal to Supercharge the Expansion of IOTA E…

### PR DESCRIPTION
**Pull request by Phyloiota**
# Welcome Community Node operators

We want to verify the outcome of the recently ended Governance vote event.

To do this, we need the help of our community node operators, who tracked this event.
 
### Event [IGP - 0005] -A Proposal to Supercharge the Expansion of IOTA EVM Growth- **IOTA HORNET**

- Open a new tab in your browser.
   - If your **IOTA Hornet** node runs on its own domain with HTTPS (like the recommended [Hornet docker setup](https://wiki.iota.org/hornet/how_tos/using_docker/) go to:
 `https://YOUR-NODES DOMAIN URL/api/participation/v1/events/0x3d2d516c4b0af81c35659666e98a83f59247dbf1698fae65ece0c5cd562a7533/status`
    (YOUR-NODEs DOMAIN URL should be your **own node**; otherwise, we all compare results from the same nodes)
   - If your node runs only HTTP go to:
`http://YOUR-NODES- IP-ADDRESS:14265/api/participation/v1/events/0x3d2d516c4b0af81c35659666e98a83f59247dbf1698fae65ece0c5cd562a7533/status`
    (YOUR-NODEs-IP - ADDRESS should be your **own node**, otherwise we all compare results from the same nodes)
 - If you use DLT.GREEN node-installer-docker:
press `E` in the dashboard and press `ENTER` to prove all events running on your node and compare the following checksum

 Check that the status of the event is "**ended**"
 

### **Now compare all checksums of your node's event data with the following ones:**

- Event [IGP - 0005]: `0xaaad6738b0526a9d74f9a5834296ff0fb108d35b401053c7b1f25ffbf386ed53`

## **Leave an approving review on this Pull request or comment "approve" If your checksums in this event matches. You can also add screenshots/proofs of your events in the comments to this PR.**

Thank you for contributing!

### CODE REVIEW

**Review by dlt-green — APPROVED** [review]
image

**Review by cbries — COMMENTED** [review]
image

**Review by TimsonLabs — COMMENTED** [review]
image

**Review by nodemagnetron — COMMENTED** [review]
event

**Review by ockerocker — COMMENTED** [review]
Bildschirmfoto vom 2024-07-29 11-20-13

**Comment by TeeVeeEss** [comment]
Approved:
```json
{
  "milestoneIndex": 12398799,
  "status": "ended",
  "questions": [
    {
      "answers": [
        {
          "value": 1,
          "current": 189453912754,
          "accumulated": 22887179400220656
        },
        {
          "value": 2,
          "current": 2435196923,
          "accumulated": 286855332145382
        },
        {
          "value": 0,
          "current": 68496514,
          "accumulated": 9283912686896
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    }
  ],
  "checksum": "0xaaad6738b0526a9d74f9a5834296ff0fb108d35b401053c7b1f25ffbf386ed53"
}
```

**Review by TeeVeeEss — COMMENTED** [review]
Approved

**Review by vromvonbeyond — COMMENTED** [review]
image

**Review by 0xKtota — COMMENTED** [review]
Approved✅
image

**Comment by DerAnhalter** [comment]
milestoneIndex	12398799
status	"ended"
questions	
0	
answers	
0	
value	1
current	189453912754
accumulated	22887179400220656
1	
value	2
current	2435196923
accumulated	286855332145382
2	
value	0
current	68496514
accumulated	9283912686896
3	
value	255
current	0
accumulated	0
checksum	"0xaaad6738b0526a9d74f9a5834296ff0fb108d35b401053c7b1f25ffbf386ed53"

**Review by DerAnhalter — COMMENTED** [review]
milestoneIndex	12398799
status	"ended"
questions	
0	
answers	
0	
value	1
current	189453912754
accumulated	22887179400220656
1	
value	2
current	2435196923
accumulated	286855332145382
2	
value	0
current	68496514
accumulated	9283912686896
3	
value	255
current	0
accumulated	0
checksum	"0xaaad6738b0526a9d74f9a5834296ff0fb108d35b401053c7b1f25ffbf386ed53"

**Review by no8ody — APPROVED** [review]
lgtm

Checksum: `0xaaad6738b0526a9d74f9a5834296ff0fb108d35b401053c7b1f25ffbf386ed53`

**Review by martinDSC10 — COMMENTED** [review]
image

**Review by Dr-Electron — APPROVED** [review]
[IGP - 0005]
Checksum: `0xaaad6738b0526a9d74f9a5834296ff0fb108d35b401053c7b1f25ffbf386ed53`

<details><summary>Details</summary>
<p>

```json
{
  "milestoneIndex": 12398799,
  "status": "ended",
  "questions": [
    {
      "answers": [
        {
          "value": 1,
          "current": 189453912754,
          "accumulated": 22887179400220656
        },
        {
          "value": 2,
          "current": 2435196923,
          "accumulated": 286855332145382
        },
        {
          "value": 0,
          "current": 68496514,
          "accumulated": 9283912686896
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    }
  ],
  "checksum": "0xaaad6738b0526a9d74f9a5834296ff0fb108d35b401053c7b1f25ffbf386ed53"
}
```

</p>
</details>

**Review by AlexTweeet — COMMENTED** [review]
Bildschirmfoto 2024-08-02 um 15 30 38

**Pull request merged**
