### PR TITLE
Verify Results [SGP - 0006] and [IGP - 0001]

### PR DESCRIPTION
**Pull request by Phyloiota**
# Welcome Community Node operators

We want to verify the outcome of the recently ended Governance vote events.

To do this, we need the help of our community node operators, who tracked these events.
 
### Event [IGP - 0001] - Shimmer Community Grant Committee Revision Proposal - **IOTA HORNET**

- Open a new tab in your browser.
   - If your **IOTA Hornet** node runs on its own domain with HTTPS (like the recommended [Hornet docker setup](https://wiki.iota.org/hornet/how_tos/using_docker/) go to:
    - https://YOUR-NODES-DOMAIN-URL/api/participation/v1/events/0x2049f52d3253ee27aa0e870cd5cd62e82676420d23b9c03c42c6d1861d01e4f3/status
    (YOUR-NODES-DOMAIN-URL should be your own node; otherwise, we all compare results from the same nodes)
    - If your node runs only HTTP go to:
    http://YOUR-NODES- IP-ADDRESS:14265/api/participation/v1/events/0x2049f52d3253ee27aa0e870cd5cd62e82676420d23b9c03c42c6d1861d01e4f3/status
    (YOUR-NODES-IP - ADDRESS should be your own node,; otherwise, we all compare results from the same nodes.)

- Check that the status of the event is "ended."

### Event [SGP - 0006] - Shimmer Community Grant Committee Revision Proposal - **SHIMMER HORNET**

- Open a new tab in your browser.
   - If your **Shimmer Hornet** node runs on its own domain with HTTPS (like the recommended [Hornet docker setup](https://wiki.iota.org/hornet/how_tos/using_docker/) go to:
    https://YOUR-NODES-DOMAIN-URL/api/participation/v1/events/0x741fc1a0ebd0e2db12b9eea5e5cc47d1eaea546784fc80ed1682dff449a2304f/status
    (YOUR-NODES-DOMAIN-URL should be your own node; otherwise, we all compare results from the same nodes.)
   - If your node runs only HTTP go to:
    http://YOUR-NODES- IP-ADDRESS:14265/api/participation/v1/events/0x741fc1a0ebd0e2db12b9eea5e5cc47d1eaea546784fc80ed1682dff449a2304f/status
    (YOUR-NODES-IP - ADDRESS should be your own node; otherwise, we all compare results from the same nodes.)

- Check that the status of the event is "ended"

### **Now compare all checksums of your node's event data with the following ones:**

- Event [IGP - 0001]: `0x67597b41d91a8429ed9f05ef3b9861f3b3307b345da686c501ce93dee1291557`
- Event [SGP - 0006]: `0x4f9dc1e19f09b6dac739d5cd7dee64fe7c3d8b9b27a7bc655b19fba36c02a9d2`

## **Leave an approving review on this Pull request or comment "approve" If your checksums in both events match. You can also add screenshots/proofs of your events in the comments to this PR.**

Thank you for contributing to this important Community work

### CODE REVIEW

**Review by 0xKtota — COMMENTED** [review]
approve ✅
[IGP - 0001] - Shimmer Grant Committee Revision Proposal
image

[SGP - 0006] - Shimmer Grant Committee revision Proposal
image

**Review by bogenlos — COMMENTED** [review]
Approved

**Review by ockerocker — COMMENTED** [review]
Event [IGP - 0001]:

Bildschirmfoto vom 2023-10-28 07-51-27

Event [SGP - 0006]:


Bildschirmfoto vom 2023-10-28 07-52-43

**Comment by JannemanDev** [comment]
image

image

**Review by JannemanDev — COMMENTED** [review]
Approve:
image

Approve:
image

**Review by no8ody — COMMENTED** [review]
Ballot ID: "0x2049f52d3253ee27aa0e870cd5cd62e82676420d23b9c03c42c6d1861d01e4f3"
Checksum: "0x67597b41d91a8429ed9f05ef3b9861f3b3307b345da686c501ce93dee1291557"

Ballot ID: "0x741fc1a0ebd0e2db12b9eea5e5cc47d1eaea546784fc80ed1682dff449a2304f"
Checksum: "0x4f9dc1e19f09b6dac739d5cd7dee64fe7c3d8b9b27a7bc655b19fba36c02a9d2"

**Review by dlt-green — COMMENTED** [review]
image

**Review by dlt-green — COMMENTED** [review]
image

**Comment by TeeVeeEss** [comment]
IOTA
```json
{
  "milestoneIndex": 8047684,
  "status": "ended",
  "questions": [
    {
      "answers": [
        {
          "value": 1,
          "current": 200527309782,
          "accumulated": 17930983583402792
        },
        {
          "value": 2,
          "current": 14200214043,
          "accumulated": 582511637632794
        },
        {
          "value": 0,
          "current": 2488133452,
          "accumulated": 138168183315125
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    }
  ],
  "checksum": "0x67597b41d91a8429ed9f05ef3b9861f3b3307b345da686c501ce93dee1291557"
}
```
Shimmer
```json
{
  "milestoneIndex": 6584901,
  "status": "ended",
  "questions": [
    {
      "answers": [
        {
          "value": 1,
          "current": 147196213359,
          "accumulated": 15451760086140298
        },
        {
          "value": 2,
          "current": 219954053,
          "accumulated": 21600109924392
        },
        {
          "value": 0,
          "current": 7589548907,
          "accumulated": 47084504636160
        },
        {
          "value": 255,
          "current": 0,
          "accumulated": 0
        }
      ]
    }
  ],
  "checksum": "0x4f9dc1e19f09b6dac739d5cd7dee64fe7c3d8b9b27a7bc655b19fba36c02a9d2"
}
```

**Review by TeeVeeEss — COMMENTED** [review]
both checksums match the ones my nodes produced

**Review by Konjunktiv — COMMENTED** [review]
Name: [SGP - 0006] - Shimmer Community Grant Committee Revision Proposal
Status: ended Milestone index: 6584901

Event ID: 0x741fc1a0ebd0e2db12b9eea5e5cc47d1eaea546784fc80ed1682dff449a2304f
Checksum: 0x4f9dc1e19f09b6dac739d5cd7dee64fe7c3d8b9b27a7bc655b19fba36c02a9d2

Total rewards:  Symbol: null

**Review by Konjunktiv — COMMENTED** [review]
Name: [IGP - 0001] - Shimmer Community Grant Committee Revision Proposal
Status: ended Milestone index: 8047684

Event ID: 0x2049f52d3253ee27aa0e870cd5cd62e82676420d23b9c03c42c6d1861d01e4f3
Checksum: 0x67597b41d91a8429ed9f05ef3b9861f3b3307b345da686c501ce93dee1291557

Total rewards:  Symbol: null

**Comment by Danlino** [comment]
ev

**Review by p00dl — COMMENTED** [review]
image

**Review by p00dl — COMMENTED** [review]
image
Ok

**Review by vromvonbeyond — COMMENTED** [review]
image

**Review by vromvonbeyond — COMMENTED** [review]
image

**Review by Travetown — COMMENTED** [review]
Bildschirmfoto 2023-10-29 um 08 28 14


Bildschirmfoto 2023-10-29 um 08 24 14
5c-4cfb-8f94-79dcf959db2d">

**Comment by ChrBender** [comment]
Approved ✅
Event [IGP - 0001]
image

**Review by dlt-green — APPROVED** [review]
100% agreement from our decentral NodePool

**Review by no8ody — APPROVED** [review]
lgtm

**Comment by 2g4y1** [comment]
Screenshot_20231029-115500

**Comment by 2g4y1** [comment]
Screenshot_20231029-115842

**Review by AlexTweeet — COMMENTED** [review]
Approve

Bildschirmfoto 2023-10-29 um 12 31 41

**Review by TimsonLabs — COMMENTED** [review]
image

image

**Review by CryptoFutta — COMMENTED** [review]
approved
231030_IGP-0001

approved
231030_SGP-0006

**Review by martinDSC10 — COMMENTED** [review]
image

**Comment by mogulbuster** [comment]
IOTAnode

**Comment by mogulbuster** [comment]
IOTAnode
ShimmerNode

**Pull request merged**
